@baseUrl = http://localhost:3333

# @name create_product

POST {{baseUrl}}/product
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

headphones
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

20
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

headphone description
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="headphones.jpg"
Content-Type: image/jpeg

< ./assets/headphone.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#####

# @name find_product

GET  {{baseUrl}}/product/38f3f766-8508-432a-af67-b8d5ff9e767d
Content-Type: application/json


#####

# @name find_all_product

GET  {{baseUrl}}/product
Content-Type: application/json

#####

# @name delete_product

DELETE {{baseUrl}}/product/38f3f766-8508-432a-af67-b8d5ff9e767d
Content-Type: application/json

#####

# @name update_product

PUT {{baseUrl}}/product/1a7adaf0-5ff6-49c1-8536-7b113879893d
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="headphones.jpg"
Content-Type: image/jpeg

< ./assets/headphone.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#####

# @name create_user

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "123456"
}

#####
# @name find_user

GET {{baseUrl}}/user/7902ef55-379a-4497-9475-a5e2a296857a
Content-Type: application/json


#####

# @name edit_user

PUT {{baseUrl}}/user/7902ef55-379a-4497-9475-a5e2a296857a
Content-Type: application/json

{
  "name": "Joao de Deus",
  "oldPassword":"123456"
}

#####

# @name edit_user

DELETE  {{baseUrl}}/user/7902ef55-379a-4497-9475-a5e2a296857a
Content-Type: application/json

#####

# @name authenticate_user

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "123456"
}